const currencyCodes = [
    "Euro (EUR)",
    "United States Dollar (USD)",
    "Japanese Yen (JPY)",
    "British Pound Sterling (GBP)",
    "Canadian Dollar (CAD)",
    "Australian Dollar (AUD)",
    "Swiss Franc (CHF)",
    "Chinese Yuan (CNY)",
    "Swedish Krona (SEK)",
    "New Zealand Dollar (NZD)",
    "South Korean Won (KRW)",
    "Singapore Dollar (SGD)",
    "Hong Kong Dollar (HKD)",
    "Norwegian Krone (NOK)",
    "Mexican Peso (MXN)",
    "Indian Rupee (INR)",
    "Russian Ruble (RUB)",
    "South African Rand (ZAR)",
    "Brazilian Real (BRL)",
    "Turkish Lira (TRY)",
    "Emirati Dirham (AED)",
    "Danish Krone (DKK)",
    "Polish Zloty (PLN)",
    "Thai Baht (THB)",
    "Malaysian Ringgit (MYR)",
    "Hungarian Forint (HUF)",
    "Indonesian Rupiah (IDR)",
    "Czech Koruna (CZK)",
    "Israeli New Shekel (ILS)",
    "Chilean Peso (CLP)",
    "Philippine Peso (PHP)",
    "Saudi Riyal (SAR)",
    "Argentine Peso (ARS)",
    "Colombian Peso (COP)",
    "Romanian Leu (RON)",
    "Peruvian Sol (PEN)",
    "Bangladeshi Taka (BDT)",
    "Kenyan Shilling (KES)",
    "Vietnamese Dong (VND)",
    "Nigerian Naira (NGN)",
    "Ukrainian Hryvnia (UAH)",
    "Moroccan Dirham (MAD)",
    "Algerian Dinar (DZD)",
    "Kazakhstani Tenge (KZT)",
    "Qatari Riyal (QAR)",
    "Egyptian Pound (EGP)",
    "Bahraini Dinar (BHD)",
    "Croatian Kuna (HRK)",
    "Sri Lankan Rupee (LKR)",
    "Omani Rial (OMR)",
    "Tunisian Dinar (TND)",
    "Guatemalan Quetzal (GTQ)",
    "Panamanian Balboa (PAB)",
    "Costa Rican Colón (CRC)",
    "Uruguayan Peso (UYU)",
    "Bolivian Boliviano (BOB)",
    "Paraguayan Guarani (PYG)",
    "El Salvadoran Colón (SVC)",
    "Honduran Lempira (HNL)",
    "Nicaraguan Córdoba (NIO)",
    "Cuban Peso (CUP)",
    "Ghanaian Cedi (GHS)",
    "Icelandic Króna (ISK)",
    "Georgian Lari (GEL)",
    "Mongolian Tögrög (MNT)",
    "Armenian Dram (AMD)",
    "Nicaraguan Córdoba (NIO)",
    "Jamaican Dollar (JMD)",
    "Malawian Kwacha (MWK)",
    "Zimbabwean Dollar (ZWL)"
];

const currencyCodeMap = {
    "euro (eur)": "eur",
    "united states dollar (usd)": "usd",
    "japanese yen (jpy)": "jpy",
    "british pound sterling (gbp)": "gbp",
    "canadian dollar (cad)": "cad",
    "australian dollar (aud)": "aud",
    "swiss franc (chf)": "chf",
    "chinese yuan (cny)": "cny",
    "swedish krona (sek)": "sek",
    "new zealand dollar (nzd)": "nzd",
    "south korean won (krw)": "krw",
    "singapore dollar (sgd)": "sgd",
    "hong kong dollar (hkd)": "hkd",
    "norwegian krone (nok)": "nok",
    "mexican peso (mxn)": "mxn",
    "indian rupee (inr)": "inr",
    "russian ruble (rub)": "rub",
    "south african rand (zar)": "zar",
    "brazilian real (brl)": "brl",
    "turkish lira (try)": "try",
    "emirati dirham (aed)": "aed",
    "danish krone (dkk)": "dkk",
    "polish zloty (pln)": "pln",
    "thai baht (thb)": "thb",
    "malaysian ringgit (myr)": "myr",
    "hungarian forint (huf)": "huf",
    "indonesian rupiah (idr)": "idr",
    "czech koruna (czk)": "czk",
    "israeli new shekel (ils)": "ils",
    "chilean peso (clp)": "clp",
    "philippine peso (php)": "php",
    "saudi riyal (sar)": "sar",
    "argentine peso (ars)": "ars",
    "colombian peso (cop)": "cop",
    "romanian leu (ron)": "ron",
    "peruvian sol (pen)": "pen",
    "bangladeshi taka (bdt)": "bdt",
    "kenyan shilling (kes)": "kes",
    "vietnamese dong (vnd)": "vnd",
    "nigerian naira (ngn)": "ngn",
    "ukrainian hryvnia (uah)": "uah",
    "moroccan dirham (mad)": "mad",
    "algerian dinar (dzd)": "dzd",
    "kazakhstani tenge (kzt)": "kzt",
    "qatari riyal (qar)": "qar",
    "egyptian pound (egp)": "egp",
    "bahraini dinar (bhd)": "bhd",
    "croatian kuna (hrk)": "hrk",
    "sri lankan rupee (lkr)": "lkr",
    "omani rial (omr)": "omr",
    "tunisian dinar (tnd)": "tnd",
    "guatemalan quetzal (gtq)": "gtq",
    "panamanian balboa (pab)": "pab",
    "costa rican colón (crc)": "crc",
    "uruguayan peso (uyu)": "uyu",
    "bolivian boliviano (bob)": "bob",
    "paraguayan guarani (pyg)": "pyg",
    "el salvadoran colón (svc)": "svc",
    "honduran lempira (hnl)": "hnl",
    "nicaraguan córdoba (nio)": "nio",
    "cuban peso (cup)": "cup",
    "ghanaian cedi (ghs)": "ghs",
    "icelandic króna (isk)": "isk",
    "georgian lari (gel)": "gel",
    "mongolian tögrög (mnt)": "mnt",
    "armenian dram (amd)": "amd",
    "jamaican dollar (jmd)": "jmd",
    "malawian kwacha (mwk)": "mwk",
    "zimbabwean dollar (zwl)": "zwl",
};

const currencySymbols = {
    eur: "€",
    usd: "$",
    jpy: "¥",
    gbp: "£",
    cad: "C$",
    aud: "A$",
    chf: "CHF",
    cny: "CN¥",
    sek: "kr",
    nzd: "NZ$",
    krw: "₩",
    sgd: "S$",
    hkd: "HK$",
    nok: "kr",
    mxn: "Mex$",
    inr: "₹",
    rub: "₽",
    zar: "R",
    brl: "R$",
    try: "₺",
    aed: "د.إ",
    dkk: "kr",
    pln: "zł",
    thb: "฿",
    myr: "RM",
    huf: "Ft",
    idr: "Rp",
    czk: "Kč",
    ils: "₪",
    clp: "CLP$",
    php: "₱",
    sar: "﷼",
    ars: "$",
    cop: "COL$",
    ron: "lei",
    pen: "S/",
    bdt: "৳",
    kes: "Ksh",
    vnd: "₫",
    ngn: "₦",
    uah: "₴",
    mad: "د.م.",
    dzd: "دج",
    kzt: "₸",
    qar: "﷼",
    egp: "£",
    bhd: "ب.د",
    hrk: "kn",
    lkr: "₨",
    omr: "﷼",
    tnd: "د.ت",
    gtq: "Q",
    pab: "B/.",
    crc: "₡",
    uyu: "$U",
    bob: "Bs",
    pyg: "₲",
    svc: "$",
    hnl: "L",
    nio: "C$",
    cup: "₱",
    ghs: "₵",
    isk: "kr",
    gel: "₾",
    mnt: "₮",
    amd: "֏",
    jmd: "J$",
    mwk: "MK",
    zwl: "Z$",
}; 

// export
export {
  currencyCodes,
  currencyCodeMap,
  currencySymbols
};